export const SN_COUNT = "count"
export const COUNT_DETAIL_PAGE_ACTIVE_UPDATED = SN_COUNT + '/DETAIL_PAGE_ACTIVE_UPDATED'
export const COUNT_ASSIGNED_WORK_EFFORTS_UPDATED = SN_COUNT + "/ASSIGNED_WORK_EFFORTS_UPDATED"
export const COUNT_DRAFT_WORK_EFFORTS_UPDATED = SN_COUNT + "/DRAFT_WORK_EFFORTS_UPDATED"
export const COUNT_IN_REVIEW_WORK_EFFORTS_UPDATED = SN_COUNT + "/IN_REVIEW_WORK_EFFORTS_UPDATED"
export const COUNT_CLOSED_WORK_EFFORTS_UPDATED = SN_COUNT + "/CLOSED_WORK_EFFORTS_UPDATED"
export const COUNT_IMPORT_SYSTEM_MESSAGES_UPDATED = SN_COUNT + "/IMPORT_SYSTEM_MESSAGES_UPDATED"
