export const SN_COUNT = "count"
export const COUNT_LIST_UPDATED = SN_COUNT + "/LIST_UPDATED"
export const COUNT_QUERY_UPDATED = SN_COUNT + "/QUERY_UPDATED"
export const COUNT_STATS_UPDATED = SN_COUNT + "/STATS_UPDATED"