export default {
    "APP_UPLOAD_VIEW": "APP_UPLOAD_VIEW",
    "APP_COUNT_VIEW": "APP_COUNT_VIEW",
    "APP_SEARCH_VIEW": "APP_SEARCH_VIEW",
    "APP_VARIANCE_LOG": "APP_VARIANCE_LOG",
    "APP_INVNTRY_CNT_IMPORT": "APP_INVNTRY_CNT_IMPORT",
    "APP_QOH_STNG_UPDATE": "APP_QOH_STNG_UPDATE",
    "INVENTORY_APP_VIEW": "INVENTORY_APP_VIEW"
} 