export default {
  "APP_DRAFT_VIEW": "APP_DRAFT_VIEW",
  "APP_ASSIGNED_VIEW": "APP_ASSIGNED_VIEW",
  "APP_PENDING_REVIEW_VIEW": "APP_PENDING_REVIEW_VIEW",
  "APP_CLOSED_VIEW": "APP_CLOSED_VIEW",
  "APP_STORE_PERMISSIONS_VIEW": "APP_STORE_PERMISSIONS_VIEW",
  "APP_SETTINGS_VIEW": "APP_SETTINGS_VIEW",
  "APP_COUNT_VIEW": "APP_COUNT_VIEW",
  "APP_PRODUCT_IDENTIFIER_UPDATE": "APP_PRODUCT_IDENTIFIER_UPDATE",
  "APP_COMMERCE_VIEW": "APP_COMMERCE_VIEW"
}