/**
 * App actions mapped to the server permissions they require.
 *
 * Views, components and routes should always refer to an action from this file instead of
 * hardcoding a server permission, so that a permission change is a one line change here.
 *
 * The value is the permission expression evaluated by `hasPermission` of the user store.
 * It supports the `OR` and `AND` operators, and an empty value means the action is allowed
 * for every logged in user.
 */
export default {
  APP_INV_COUNT_ADMIN: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_ASSIGNED_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_PENDING_REVIEW_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_CLOSED_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_DRAFT_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_EXPORT_HISTORY_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_STORE_PERMISSIONS_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_PWA_STANDALONE_ACCESS: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_BARCODE_IDENTIFIER_UPDATE: "COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_COUNT_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INVCOUNT_APP_VIEW",
  APP_VARIANCE_VIEW: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INV_COUNT_VAR_LOG",
  APP_START_FUTURE_COUNT: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INV_COUNT_PRE_START",
  APP_SESSION_LOCK_RELEASE: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INV_COUNT_LOCK_RLS",
  APP_MANAGE_COUNT_PROGRESS: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INV_COUNT_SUBMIT",
  APP_INV_CNT_VIEW_QOH: "COMMON_ADMIN OR INV_COUNT_ADMIN OR INV_CNT_VIEW_QOH",
  APP_PREVIEW_COUNT_ITEM: "PREVIEW_COUNT_ITEM OR COMMON_ADMIN OR INV_COUNT_ADMIN",
  APP_PRODUCT_IDENTIFIER_UPDATE: "COMMON_ADMIN",
  APP_COMMERCE_VIEW: "COMMERCEUSER_VIEW"
} as const satisfies Record<string, string>
