export default {
    "APP_UPLOAD_VIEW": "APP_UPLOAD_VIEW",
    "APP_COUNT_VIEW": "APP_COUNT_VIEW",
    "APP_SEARCH_VIEW": "APP_SEARCH_VIEW",
    "APP_VARIANCE_LOG": "APP_VARIANCE_LOG",
    "APP_INVNTRY_CNT_IMPORT": "APP_INVNTRY_CNT_IMPORT",
    "APP_PRODUCT_IDENTIFIER_UPDATE": "APP_PRODUCT_IDENTIFIER_UPDATE",
    "APP_QOH_STNG_UPDATE": "APP_QOH_STNG_UPDATE",
    "INVCOUNT_APP_VIEW": "INVCOUNT_APP_VIEW"
} 