export default {
    "APP_UPLOAD_VIEW": "COMMON_ADMIN",
    "APP_COUNT_VIEW": "",
    "APP_SEARCH_VIEW": "",
    "APP_VARIANCE_LOG": "FULFILL_INVCUNT_ADMIN OR INV_COUNT_ADMIN",
    "APP_INVNTRY_CNT_IMPORT": "COMMON_ADMIN"
} as any 