export default {
  "APP_UPLOAD_VIEW": "FULFILL_INVCUNT_ADMIN OR INV_COUNT_ADMIN",
  "APP_COUNT_VIEW": "",
  "APP_SEARCH_VIEW": "",
  "APP_VARIANCE_LOG": "FULFILL_INVCUNT_ADMIN OR INV_COUNT_ADMIN",
  "APP_INVNTRY_CNT_IMPORT": "",
  "APP_QOH_STNG_UPDATE": "COMMON_ADMIN",
  "APP_INVCUNT_ADMIN": "COMMON_ADMIN",
  "INVCOUNT_APP_VIEW": "INVCOUNT_APP_VIEW"
} as any 