name: Verify build

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  call-workflow-in-another-repo:
    uses: hotwax/accxui/.github/workflows/common-pull-request.yml@main
    with:
      config-path: .github/labeler.yml
      app: hotwax/inventory-count
      appDir: cycle-count
    secrets:
      envPAT: ${{ secrets.envPAT }}